Numpy is a fundamental library for scientific computing in python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

In [1]:
# import numpy
import numpy as np 
data = np.array([1,2,3,4])
print(data)
print(type(data))
print(data.shape)
data1 = np.array([2,3,4,5])
print(data1)
print(data1.shape)
print(data1.reshape(1,4)) # this will convert now in 2d (1,4 -> means 1 row, 4 columns)
print(data1)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)
[2 3 4 5]
(4,)
[[2 3 4 5]]
[2 3 4 5]


Note: We can check the array is 1d or 2d by looking in output if single [] mean 1d and [[]] mean 2d

In [2]:
# Arange in numpy
import numpy as np
arr =([1,2,3,4,5,6,7,8,9,10])
np.arange(1,10,3)
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [3]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
import sys, numpy as np, pandas as pd
print("python executable:", sys.executable)
print("numpy:", np.__version__)
print("pandas:", pd.__version__)


python executable: c:\Users\shubu\Envs\Study23_venv\Scripts\python.exe
numpy: 2.3.5
pandas: 2.3.3


You can explicity convert or cast an array from one data type to another using ndarray's astype method.

In [16]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr1.dtype
float_arr = arr1.astype(np.float64)
print(float_arr)

#If you have an array of strings representing numbers, you can use astype to convert them to numeric form:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=str)
numeric_strings.astype(float)
print(numeric_strings)


[1. 2. 3. 4. 5.]
['1.25' '-9.6' '42']


In [23]:
# Another Array dtype attribute:
int_array = np.arange(10)
new_arr = np.array([.22,3.14,2.718,.57721,.301],dtype=np.float64)
int_array.astype(new_arr.dtype)
print(int_array.astype(new_arr.dtype))
print(int_array)
print(new_arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]
[0.22    3.14    2.718   0.57721 0.301  ]


# Arithmetic with Numpy Arrays
Arrays enables you to express batch operations on data without writing any loops. Numpy user call this *Vectorization*
Any arithmetic operations between equal-size arrays apply the operation *element-wise*.
* Evaluating operations between differently sized arrays is called *broadcasting*

In [25]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
print(arr * arr)
print(arr - arr)    
print(arr + arr)
print(arr / arr)
print(1/arr)
                             

[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


# Basic Indexing and slicing
arr[2:4]=23 This value is propagated(or broadcast henceforth) to the entire selection.
The "bare" slice[:] will assign to all values in an array

***Arr3d[0][1][2] - [0] means block [1] means index from that block [2] element from that index***


In [46]:
arr = np.arange(20)
print(arr)
print(arr[4])
print(arr[5:8])
print(arr[5:8:2])
arr[2:6]=23 # This will assign 23 to index 2 and 3
print(arr)
arr_slice = arr[2:6] # [2:4] means index 2 and 3 but it is [0,1] in arr_slice
print(arr_slice) # 23 now it is 23 in entire selection
arr_slice[0] = 37# changing index 3 value to 37
# arr_slice[:] = 100 # this will assign 100 to entire selection
print(arr)
print(arr_slice)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
4
[5 6 7]
[5 7]
[ 0  1 23 23 23 23  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[23 23 23 23]
[ 0  1 37 23 23 23  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[37 23 23 23]


In [ ]:
# 2d Array
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)    
print(arr2d[2]) # it will print 3rd row
print(arr2d[1][0]) # these are row and columns 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[7 8 9]
4


In [ ]:
# Multidimensional array indexing
arr3d = np.array([
    [[1,2,3],[3,4,5]],
    [[7,7,8],[9,10,11]]
    ])
print(arr3d)
# print(arr3d[0])
# print(arr3d[1])
print(arr3d[0][1][2]) # it will print 5

[[[ 1  2  3]
  [ 3  4  5]]

 [[ 7  7  8]
  [ 9 10 11]]]
5
