Numpy is a fundamental library for scientific computing in python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

In [16]:
# import numpy
import numpy as np 
data = np.array([1,2,3,4])
print(data)
print(type(data))
print(data.shape)
data1 = np.array([2,3,4,5])
print(data1)
print(data1.shape)
print(data1.reshape(1,4)) # this will convert now in 2d (1,4 -> means 1 row, 4 columns)
print(data1)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)
[2 3 4 5]
(4,)
[[2 3 4 5]]
[2 3 4 5]


Note: We can check the array is 1d or 2d by looking in output if single [] mean 1d and [[]] mean 2d

In [17]:
# Arange in numpy
import numpy as np
arr =([1,2,3,4,5,6,7,8,9,10])
np.arange(1,10,3)
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr1= np.array([1,2,3], dtype = np.float64)
arr1

You can explicity convert or cast an array from one data type to another using ndarray's astype method.