Numpy is a fundamental library for scientific computing in python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

In [1]:
# import numpy
import numpy as np 
data = np.array([1,2,3,4])
print(data)
print(type(data))
print(data.shape)
data1 = np.array([2,3,4,5])
print(data1)
print(data1.shape)
print(data1.reshape(1,4)) # this will convert now in 2d (1,4 -> means 1 row, 4 columns)
print(data1)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)
[2 3 4 5]
(4,)
[[2 3 4 5]]
[2 3 4 5]


Note: We can check the array is 1d or 2d by looking in output if single [] mean 1d and [[]] mean 2d

In [1]:
# Arange in numpy
import numpy as np
arr =([1,2,3,4,5,6,7,8,9,10])
np.arange(1,10,3) # it will start from 1 to 10 with step size of 3
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
np.ones((4,4)) # it will create 4x4 matrix with all values as 1

You can explicity convert or cast an array from one data type to another using ndarray's *astype method*.

In [2]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr1.dtype
float_arr = arr1.astype(np.float64)
print(float_arr)

#If you have an array of strings representing numbers, you can use astype to convert them to numeric form:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=str)
numeric_strings.astype(float)
print(numeric_strings)


[1. 2. 3. 4. 5.]
['1.25' '-9.6' '42']


In [3]:
# Another Array dtype attribute:
int_array = np.arange(10)
new_arr = np.array([.22,3.14,2.718,.57721,.301],dtype=np.float64)
int_array.astype(new_arr.dtype)
print(int_array.astype(new_arr.dtype))
print(int_array)
print(new_arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]
[0.22    3.14    2.718   0.57721 0.301  ]


# Arithmetic with Numpy Arrays
Arrays enables you to express batch operations on data without writing any loops. Numpy user call this *Vectorization*
Any arithmetic operations between equal-size arrays apply the operation *element-wise*.
* Evaluating operations between differently sized arrays is called *broadcasting*

In [ ]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
print(arr * arr)
print(arr - arr)    
print(arr + arr)
print(arr / arr)
print(1/arr)
                             

# Basic Indexing and slicing
The "bare" slice[:] will assign to all values in an array

***Arr3d[0][1][2] - [0] means block [1] means index from that block [2] element from that index***


In [ ]:
arr = np.arange(20)
print(arr)
print(arr[4])
print(arr[5:8])
print(arr[5:8:2])
arr[2:6]=23 # This will assign 23 to index 2 and 3
print(arr)
arr_slice = arr[2:6] # [2:4] means index 2 and 3 but it is [0,1] in arr_slice
print(arr_slice) # 23 now it is 23 in entire selection
arr_slice[0] = 37# changing index 3 value to 37
# arr_slice[:] = 100 # this will assign 100 to entire selection
print(arr)
print(arr_slice)



In [ ]:
# 2d Array
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)    
print(arr2d[2]) # it will print 3rd row
print(arr2d[1][0]) # these are row and columns 

In [ ]:
# Multidimensional array indexing
arr3d = np.array([
    [[1,2,3],[3,4,5]],
    [[7,7,8],[9,10,11]]
    ])
print(arr3d)
print(arr3d[0])
print(arr3d[1])
print(arr3d[0][1][2]) # it will print 5

In [ ]:
# Indexing with slices
# arr[:2] means from beginning to index 2 (not including 2)
# Note: [:] means to take the entire axis.
import numpy as np
arr = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]    
])
print(arr.shape)
print(arr[:3,2:]) # it will print all rows and columns from index 0 to 1
print(arr[:3,2:].shape) # it will print all rows and columns from index 2 to end
print(arr[:3,2:4])
print(arr[:3,2:4].shape)

# assiging to a slice expression 
arr[:,3:] = 0
print(arr)

# Boolean Indexing and Fancy Indexing
* Boolean comparisons (such as ==)
- The Boolean array must be of the same length as the array axis it's indexing. You can also even mix and match Boolean arrays with slices or integers.
* ~ The operator can be useful when you want to invert a Boolean array refernced by a variable.
*The python keywords AND and OR do not work with boolean arrays. Use &(AND) and |(OR) instead.

* *Fancy indexing* is term adopted by Numpy to describe indexing using integer arrays.(8*4 array)
- If you assign any values with fancy indexing, the indexed values will be modified.


In [ ]:
import numpy as np
names = np.array(['shiva','sakshi','shiva','sakshi','shivalika','rohit','rohit','shalu','rohit'])
data = np.array([[-1,2,-3],[4,-5,-6],[7,8,9],[10,11,12],[13,14,15],[16,17,18],[19,20,21],[22,23,24],[25,26,27]])
print(names)
print(data) 
# print(names == 'shiva') # it will print boolean array
# data[names == 'shiva'] # it will print all rows where name is shiva
print(data[names == 'sakshi', :])# it will print all rows where name is sakshi
print(data[names == "sakshi", 2:]) # it will print all rows where name is sakshi from index 2 to end

# # To select everyone except 'shiva'
print(data[names != 'shiva'])
print(names != 'shiva')
print(~(names == 'rohit')) # Returns false for rohit and true for others
print(data[~(names == 'rohit')])
new_arr = names == 'shalu'
print(~new_arr)
print(data[~new_arr])

# Combine multiple Boolean conditions
new_list = (names == 'shiva') | (names == 'sakshi')
print(new_list)
print(data[new_list])
data[data < 0 ] = 0
print(data)
data[names != 'shalu'] = 7
print(data)





In [ ]:
# passing multiple indices
arr = np.arange(32).reshape((8,4))
print(arr)
print(arr[[0,1,2,3],[0,1,2,3]])
arr[[0,1,2,3],[0,1,2,3]] = 0
print(arr[[0,1,2,3],[0,1,2,3]])

# Fancy Indexing
arr = np.zeros((8,4))
for i in range(8):
    arr[i] =i
print(arr)
print(arr[[1,2,3,4,5]])
print(arr[[-1,-2,-3,-4]])


# Transposing Arrays and Swapping Axes
Transposing is special form of reshaping that similarly returns a view on the underlying data without copying anything. Arrays have the transpose method and the special *T attribute*
- When computing the inner matrix product using numpy.dot
- The @ infix operator is another way to do matrix multiplication.
*Swapaxes* which takes a pair of axis numbers and switches the indicated axes to rearrange the data.
- Swapaxes similarly returns a view on the data without making a copy.

In [ ]:
import numpy as np
arr = np.arange(15).reshape((3,5))
print(arr)
print(arr.T)
arr1 = np.array([[1,2,3],[4,5,6],[6,7,8],[12,13,14],[0,0,0]])
print(arr1)
print(np.dot(arr. T, arr)) # it will give inner matrix product
print(arr. T @arr) # it will give inner matrix product
print(arr1.swapaxes(0,1)) # it will swap the axis 0 and 1

[[ 1  2  3]
 [ 4  5  6]
 [ 6  7  8]
 [12 13 14]
 [ 0  0  0]]
[[ 1  4  6 12  0]
 [ 2  5  7 13  0]
 [ 3  6  8 14  0]]
