# Pseudorandom Number Generation
1. numpy.random is python built-in module.
2. Generates one number at a time.
3. Very slow for large amounts of random numbers.

* Numpy's random module
1. Generates many numbers at once (vectorized).
2. Much faster, especially for big samples.

*NumPy is fast because it works on entire arrays at once* Python's random works one-by-one, which is slow.

### Pseudorandom
1. The numbers are not truly random.
2. They are generated using a formula inside the computer.\
*Pseudorandom = random-looking numbers created by a formula*
*They feel random, but can be reproduced using a seed*.

### Numpy's default random number generator *numpy.random.*\
``` np.random.standard_normal(3) ```\
randint generates random integers within a specified range.\
``` numpy.random.randint(low, high=None, size=None) ```


#### What is a "generator object" (rng)?
*Think of a generator as a separate random machine.*\
``` rng = np.random.default_rng(seed =12345) ```
* This line:
1. Create a new random generator
2. That generator will always produce the same sequence of random numbers if you use the same seed.

*A seed sets the starting point of the random number formula.*

*Benefits of using your own rng:*

1. Keeps randomness isolated.
2. Makes your code reproducible.
3. Avoids interference with other parts of code using numpy random.
4. Recommended in modern NumPy.

In [5]:
import numpy as np
new = np.random.standard_normal(size=(4,4)) # it will create 4x4 matrix with random values
# print(new)
rng = np.random.default_rng(12345) # it will create random number generator with seed 12345
# print(rng.random((2,3))) # it will create 2x3 matrix with random values using above rng
# print(type(rng))
print(rng.integers(0,10,size=(3,4))) # it will create 3x4 matrix with random integers between 0 to 10 using above rng   
print(rng.permutation(10)) # it will create random permutation of numbers from 0 to 9 using above rng

[[6 2 7 3]
 [2 7 6 6]
 [9 3 8 3]]
[0 8 3 7 2 6 9 5 4 1]
