# Universal Functions: Fast Element-Wise Array Functions
A universal function, or *ufunc* is a function that performs element-wise operations on data in ndarrays. You can think of them as fast vectorized wrappers for simple functions that take one or more scalar values and produce one or more scalar results. example *numpy.sqrt or numpy.exp* -> These are referred to as unary ufuncs.
others, such as numpy.add or numpy.maximum, take two arrays thus *binary ufuncs* and return a single as result.
1. Ufuncs accept an optional out argument that allows them to assign their results into an existing array rather than create a new one.\
``` out = np.zeros _like(arr) ```

#### numPy.where
The numpy.where function is vectorized version of the ternary expression x if condition else y.\
``` result = np.where(cond, xarr, yarr) ```
*A typical use of where in data analysis is to produce a new array of values based on another array*
Suppose you had a matrix of randomly generated data and you wanted to replace all positive values with 2 and all negative values with -2.This is possible to do with *numpy.where*

#### Mathematical and statistical methods
A set of mathematical functions that compute statistics about an entire array or about the data along an axis are accessible as methods of the array class. You can use aggregations(sometimes called reductions) like sum, mean and std(standard deviation) either by calling the array instance method or using the top-level Numpy function.\ *When you use the Numpy function, like numpy.sum, you have to pass the array you want to aggregate as the first argument*

1. Functions like mean and sum take an optional axis argument that computes the statistic over the given axis, resulting in an array with one less dimension.
2. cumsum cumulative sum of elements starting from 0
3. cumprod cumulative product of elements starting from 1

#### Methods for Boolean arrays

Boolean values are coerced to 1 (true) and 0 (false) in the preceding methods. Thus, sum is often used as a means of counting True values in a Boolean array.
1. The parentheses here in the expression (arr>0).sum() are necessary to be able to call sum() on the temporary result of arr>0.
2. Two additional methods, any and all, are useful especially for Boolean arrays
*arrays.any tests whether one or more values in an array is True.*\ *arrays.all checks if every value is True.*\
These methods also work with non-Boolean arrays, where non-zero elements are treated as True.

#### Unique and other Set Logic
Numpy has some basic set operations for one dimensional ndarrays. A commonly used one is *numpy.unique*, which returns the sorted unique values in an array\ Another Function, *numpy.isin* tests membership of the values in one array in another, returning a Boolean array

#### File Input and Output With Arrays
 1. numpy. save and numpy.load are the two workhorse functions for efficiently saving and loading array data on disk.
 *Arrays are saved by default  in an uncopressed raw in binary formats with file extension .npy
 

In [ ]:
# Ufunc
import numpy as np
arr = np.arange(10)
print(np.sqrt(arr)) # unary ufunc
print(np.exp(arr))
rng = np.random.default_rng(1)
x = rng.standard_normal((8,))
y = rng.standard_normal((8,))  
print(np.maximum(x, y)) # binary ufunc
print(np.add(x,y))



[ 0.03675258  0.46485443  0.99131123 -0.90947169  0.7160676   0.33912372
 -0.61085971]
[ 1.  2.  0. -3.  2.  1. -1.]


In [ ]:
arr1 = rng.standard_normal(7) * 3
remainder, whole_part = np.modf(arr1) # return fractional and integral parts
print(remainder)
print(whole_part)

#### Out argument 
When we wirite *np.add(arr,1)* Numpy creates a brand-new array in memory to store the results.\
But if you give an out argument, you are telling Numpy:\ *Don't create new array. Put the result inside This Existing array*

Benefits:\ 
1. Avoids memory allocation -> faster  for big arrays
2. In-place operations
3. Useful in performance-critical code

In [15]:
import numpy as np
arr = np.arange(12)
out = np.empty_like(arr)
print(np.add(arr,1))
print(out)
np.add(arr, 1, out=out)
print(out)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# np.where
x = np.array([1,2,3,4,5])
y = np.array([9,8,7,6,5])   
condition = np.array([True, False, True, False, True])
result = np.where(condition, x, y)  # if condition is True, take from x else from y
# print(result)  # Output: [1 8 3 6 5]

arr = rng.standard_normal((4,4))
print(arr>0)
print(np.where(arr<0,2,-2)) # set negative values to -2, positive to 2
print(np.where(arr>0,2,arr)) # set positive values to 2, keep others unchanged 

[[False False  True  True]
 [False False False  True]
 [ True  True False  True]
 [ True  True  True  True]]
[[ 2  2 -2 -2]
 [ 2  2  2 -2]
 [-2 -2  2 -2]
 [-2 -2 -2 -2]]
[[-0.51224273 -0.81377273  2.          2.        ]
 [-0.11394746 -0.84015648 -0.82448122  2.        ]
 [ 2.          2.         -0.66550971  2.        ]
 [ 2.          2.          2.          2.        ]]


In [29]:
arr = rng.standard_normal((4,4))
print(np.mean(arr))
print(np.mean(arr, axis=0)) # column-wise mean
print(np.mean(arr, axis=1)) # row-wise mean 

arr1 = np.arange(10)
print(np.cumsum(arr1)) # cumulative sum
print(np.cumprod(arr1 + 1)) # cumulative product

arr2 = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(np.cumsum(arr2, axis=0)) # column-wise cumulative sum    

0.08255407204989426
[-0.137465   -0.22201475  0.83930199 -0.14960595]
[-0.62439275  0.40423791  0.1837406   0.36663054]
[ 0  1  3  6 10 15 21 28 36 45]
[      1       2       6      24     120     720    5040   40320  362880
 3628800]
[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]


In [35]:
# Methods for Boolean Arrays
arr = rng.standard_normal(100)
print((arr > 0).sum()) # count of positive values
print((arr < 0).sum()) # count of negative values
print((arr < 0).any()) # check if any negative value exists
print((arr > 0).all()) # check if all values are positive

#sorting
arr = rng.standard_normal(10)   
print(np.sort(arr)) # sorted array

# Unique and Other Set Logic
arr = np.array([1,2,3,2,3,4,5,5,6,7,8,8,9])
print(np.unique(arr)) # unique values
print(np.intersect1d([1,2,3,4],[3,4,5,6])) # intersection
print(np.union1d([1,2,3,4],[3,4,5   ,6])) # union

values = np.array([5,10,15,20,25,30,35,40,45])
print(np.isin([10,20,50], values)) # check membership

45
55
True
False
[-1.01506791 -0.9208504  -0.89313062 -0.3717167  -0.2992647   0.01145129
  0.85501932  1.13604868  1.7851684   2.04875565]
[1 2 3 4 5 6 7 8 9]
[3 4]
[1 2 3 4 5 6]
[ True  True False]
