#### Array-Oriented Programming With Arrays 
Instead of writing loops (for while) again and again, Numpy lets you do calculations on entire arrays at once this is called as Vectorization.
*numpy.meshgrid takes two 1-D array (x&y) and create two 2-D grids So that you can compute Something for every pair(x,y)
Benefits:
1. graphs
2. 3d surfaces
3. heatmaps
 
#### Random Walks
You start at 0 and repeatedly take a step:
+1 or -1 50% chance.
*Instead of simulating ONE wall with a loop, Numpy lets you simulate thousands of walks together using arrays.*
np.abs -> It turns negative number into positive number and leaves positive number as they are.
*Numpy can process 5000 * 1000 operations instantly perfect Example(Vectorization).

Important Notes:
1. Only square matrices have inverses
2. Not all square matrices are invertible (e.g., determinant = 0 → NOT invertible)
 

In [1]:
# Random Walks
import numpy as np
points = np.arange(-5, 5, 0.1)
xs, ys = np.meshgrid(points, points)
# print(xs)
# print(ys)
# z = np.sqrt(xs**2 + ys**2)
# print(z)

# import matplotlib.pyplot as plt
# plt.imshow(z, cmap=plt.cm.viridis) 
# plt.colorbar()
# plt.title("Image of above equation")
# plt.show()


nsteps = 1000
rng = np.random.default_rng(seed = 12345)
draws = rng.integers(0, 2, size=nsteps)         
steps = np.where(draws == 0, 1, 0)
walk = steps.cumsum()
print(walk) 
print("Maximum position:", walk.max())
print("Minimum position:", walk.min())

[  0   1   1   2   3   3   3   3   3   4   4   5   5   5   6   7   8   8
   8   8   8   9   9   9   9   9  10  11  12  13  14  14  15  15  16  17
  18  18  18  19  19  20  21  22  22  23  24  25  26  27  27  27  28  29
  30  31  32  33  34  34  34  34  34  34  35  35  35  35  35  35  35  35
  35  35  36  36  36  37  38  39  39  40  40  40  40  41  41  41  42  43
  44  45  45  46  46  47  48  49  50  50  51  52  52  53  53  53  54  55
  56  57  57  58  58  59  59  60  60  61  62  63  63  64  65  66  66  67
  67  68  68  69  69  70  70  71  71  72  72  72  73  74  75  75  75  76
  77  77  78  78  78  79  79  79  80  81  82  83  84  84  84  84  85  85
  86  87  87  88  88  88  88  89  89  89  89  90  91  91  91  92  92  93
  94  95  96  97  97  97  97  97  97  98  98  99 100 101 101 101 102 103
 104 105 106 107 108 109 109 109 110 111 112 112 112 113 114 114 115 116
 117 118 119 120 121 122 123 124 125 125 125 125 126 127 127 127 127 128
 128 128 129 129 129 130 130 131 131 132 132 133 13

In [2]:
# Linear Algebra
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[6, 23], [-1, 7], [8, 9]])
# print(A,B)
print(A.dot(B))
print(np.dot(A, B)) # both are same
print(A @ B)  # same as above two
# A matrix product between two-dimensional arrays and a suitably sized one-dimensional array results in a one-dimensional array.
print(A @ np.ones(3))

#numpy.linalg has a standard set of matrix decompositions and things like inverse and determinant and determinant.
from numpy.linalg import inv, qr
x = rng.standard_normal((5, 5))
mat = x.T @ x
print(mat)
print(inv(mat))
print(mat @ inv(mat))  # should be identity matrix

[[ 28  64]
 [ 67 181]
 [106 298]]
[[ 28  64]
 [ 67 181]
 [106 298]]
[[ 28  64]
 [ 67 181]
 [106 298]]
[ 6. 15. 24.]
[[ 2.60406199 -3.97932832 -1.95335549 -1.00721699 -0.57506875]
 [-3.97932832 11.41724992  7.67538132  1.21463943 -1.96085975]
 [-1.95335549  7.67538132  7.77011039  2.76011172 -1.42164137]
 [-1.00721699  1.21463943  2.76011172  3.55102322  1.25871936]
 [-0.57506875 -1.96085975 -1.42164137  1.25871936  1.953983  ]]
[[13.61432166  8.38887744 -2.14768118 -1.54078206 11.8551507 ]
 [ 8.38887744  5.57415621 -1.97991637 -0.43494269  6.90234237]
 [-2.14768118 -1.97991637  1.9570517  -1.33410973 -0.33567705]
 [-1.54078206 -0.43494269 -1.33410973  2.18987    -3.27125394]
 [11.8551507   6.90234237 -0.33567705 -3.27125394 12.79050554]]
[[ 1.00000000e+00  3.84820368e-15 -2.12659187e-15  3.24259690e-17
   2.37151797e-15]
 [-6.81789039e-17  1.00000000e+00 -4.35773830e-16 -1.31944629e-16
  -2.24711543e-15]
 [-2.45409076e-15  3.88387799e-15  1.00000000e+00 -6.72052399e-16
   2.26247794e-1