In [ ]:
# Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
import numpy as np
arr = np.random.randint(1,20, size =(5,5))

print("Array",arr)
arr[:,2]=1
print(arr)

# Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

arr1 = np.random.randint(1,16, size =(4,4))
print("Array",arr1)
np.fill_diagonal(arr1,0) # Replace diagonal elements with 0
print(arr1)

In [ ]:
# 1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
import numpy as np
# array = np.arange(1, 37).reshape((6, 6))  (method -2 to create the array)
arr = np.random.randint(1,36, size =(6,6))
print(arr)
print(arr[2:5,1:4])

# 2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.
arr = np.arange(1,26).reshape(5,5)
print(arr)
print("Border elements:",arr[0,:],arr[-1,:],arr[:,0],arr[:,-1])

In [ ]:
# 1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
import numpy as np
# arr1 = np.random.randint(1,12, size =(3,4))
# arr2 = np.random.randint(1,12, size =(3,4))
# print(arr1 + arr2)
# print(arr1 - arr2)
# print(arr1 * arr2)
# print(arr1 / arr2)  

# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

arr = np.arange(1,17).reshape(4,4)
# print(arr)
print(arr.cumsum(axis=0)) # sum along rows
print(arr.cumsum(axis=1)) # sum along columns

In [ ]:
# 1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
import numpy as np
arr = np.random.randint(1,26, size=(5,5))
# print(arr)
# print(np.mean(arr))
# print(np.median(arr))
# print(np.median(arr))
# print(np.std(arr))
# print(np.var(arr))


# 2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

arr= np.arange(1,10).reshape(3,3)
print(arr)
print(np.mean(arr))
normalized_array = (arr - np.mean(arr)) / np.std(arr)
print(normalized_array)

In [ ]:
# 1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
arr1= np.random.randint(1,11,size =(3,3))
arr2 = np.random.randint(1,11, size =(3,))
print(arr1 + arr2)

# 2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.
arr1= np.random.randint(1,17,size =(4,4))
arr2 = np.random.randint(1,17, size =(4,))
print(arr2-arr1)


In [ ]:
# 1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
import numpy as np
from numpy.linalg import det, inv,eig
arr = np.random.randint(1,10, size = (3,3))
print(det(arr))
print(inv(arr))
print(eig(arr))

# 2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.
arr = np.random.randint(1,11, size = (2,3))
arr1 = np.random.randint(1,11, size = (3,2))
print(arr.T)
print(arr.dot(arr1)) # for matrix multiplication
print(np.dot(arr,arr1))


195.0


In [ ]:
# 1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
arr = np.arange(1,10).reshape(3,3)
print(arr)
print(arr.reshape(1,9))
print(arr.reshape(9,1))

# 2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).
arr = np.random.randint(1,26, size =(5,5))
print(arr)
print(arr.flatten)
print(arr.reshape(5,5))

[[ 9 20 24 24  4]
 [18 23  7 11  7]
 [21  7 19  9 23]
 [19 11 24 15 20]
 [18 15 14 17 11]]
<built-in method flatten of numpy.ndarray object at 0x000001531FA62850>
[[ 9 20 24 24  4]
 [18 23  7 11  7]
 [21  7 19  9 23]
 [19 11 24 15 20]
 [18 15 14 17 11]]


In [ ]:
# 1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
arr = np.random.randint(1,26, size =(5,5))
print(arr)
print(arr[[0,0,-1,-1],[0,-2,0,-1]]) # corner elements


# 2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

arr = np.random.randint(1,17, size =(4,4))
arr[arr>10] = 10
print(arr)

[[10 10 10 12]
 [10 14 10 10]
 [10 10 10 10]
 [10 11 16 10]]


In [ ]:
# 1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
dtype = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = [('Alice', 25, 55.5), ('Bob', 22, 70.0), ('Charlie', 30, 68.0)]
arr = np.array(data, dtype=dtype)   
sorted_arr = np.sort(arr, order='age')
print(sorted_arr)


#### Masked array
*A masked array is an array where some entries are marked as invalid, missing, or not to be used.
These “masked” elements are not included in computations.*
A masked array pairs:
1. the real data (an ndarray) and
2. a mask (a boolean ndarray of the same shape).

Mask semantics:
mask==True → that element is invalid / ignored.
mask==False → element is valid and used in calculations

In [85]:
# 1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
import numpy as np
import numpy.ma as ma
arr = np.random.randint(1,20, size =(4,4))
masked_arr = ma.masked_greater(arr,10)
print(arr)
print(masked_arr)




[[10 11 17  1]
 [ 1  4 10 10]
 [15 12 18 16]
 [ 1 11 13  7]]
[[10 -- -- 1]
 [1 4 10 10]
 [-- -- -- --]
 [1 -- -- 7]]
